# Generated by Django 5.1.1 on 2024-09-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=80)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('assunto', models.CharField(choices=[('Orçamento', 'Orçamento'), ('Projetos', 'Projetos'), ('Serviço', 'Serviço'), ('Dúvidas', 'Dúvidas'), ('Outros', 'Outros')], default='Orçamento', max_length=10)),
                ('mais_informacoes', models.TextField()),
            ],
        ),
    ]
