# Generated by Django 5.1.1 on 2024-09-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_formulario_assunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='assunto',
            field=models.CharField(choices=[('Orçamento', 'Orçamento'), ('Projeto', 'Projeto'), ('Serviço', 'Serviço'), ('Dúvida', 'Dúvida'), ('Outro', 'Outro')], default='orcamento', max_length=10),
        ),
    ]
