# Generated by Django 5.1.1 on 2024-09-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_formulario_assunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='assunto',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('projeto', 'Projeto'), ('servico', 'Serviço'), ('duvida', 'Dúvida'), ('outro', 'Outro')], default='orcamento', max_length=10),
        ),
    ]
